services:
  peerbanhelper:
    image: @IMAGE@
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - "/${TRIM_APPDEST_VOL}/@appshare/peerbanhelper/data:/app/data"
    network_mode: host
    stop_grace_period: 30s