version: "3.9"

services:
  peerbanhelper:
    image: ghostchu/peerbanhelper:v9.2.5
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - "./data:/app/data"
    network_mode: host
    stop_grace_period: 30s